# Generated by Django 4.1.1 on 2022-09-18 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mobileproduction_merchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproduction',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=10), size=8), default='{}', size=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='connect_tecnology',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='fast_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='os',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
