# Generated by Django 4.1.1 on 2022-09-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mobileproduction_color_mobileproduction_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileproduction',
            name='color',
        ),
    ]
