# Generated by Django 4.1.1 on 2022-09-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('products', '0004_remove_mobileproduction_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileproduction',
            name='merchat',
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.merchant'),
        ),
    ]
