# Generated by Django 4.1.1 on 2022-09-19 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_mobileproduction_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileproduction',
            name='promotions',
        ),
        migrations.AddField(
            model_name='mobileproduction',
            name='promotion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
