# Generated by Django 4.1.1 on 2022-09-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_mobileproduction_promotions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileproduction',
            old_name='promotion',
            new_name='dicount',
        ),
    ]
