# Generated by Django 4.1.1 on 2022-09-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_promotion_mobileproduction_dicount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileproduction',
            old_name='dicount',
            new_name='discount',
        ),
    ]
