# Generated by Django 4.1.1 on 2022-09-20 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_dicount_mobileproduction_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileproduction',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
