# Generated by Django 4.1.1 on 2022-09-20 08:51

from django.db import migrations, models
import django.db.models.deletion
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_mobileproduction_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/products', validators=[products.validators.image_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.mobileproduction')),
            ],
        ),
    ]
