# Generated by Django 4.1.1 on 2022-09-15 15:05

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='merchant',
            new_name='is_merchant',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255)),
                ('card_image_front', models.ImageField(upload_to='midea/images/merchant/front', validators=[accounts.validators.image_size])),
                ('card_image_back', models.ImageField(upload_to='midea/images/merchant/back', validators=[accounts.validators.image_size])),
                ('is_active', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
