# Generated by Django 4.1.1 on 2022-09-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_rename_merchant_customer_is_merchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='customer',
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
