# Generated by Django 4.1.1 on 2022-09-16 14:47

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_merchant_customer_merchant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='card_image_back',
            field=models.ImageField(null=True, upload_to='midea/images/merchant/back', validators=[accounts.validators.image_size]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='card_image_front',
            field=models.ImageField(null=True, upload_to='midea/images/merchant/front', validators=[accounts.validators.image_size]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='cart_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
