# Generated by Django 4.1.1 on 2022-09-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_merchant_card_image_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='is_active',
            new_name='is_active_user',
        ),
    ]
