# Generated by Django 4.1.1 on 2022-09-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_active_merchant_is_active_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_merchant',
            new_name='is_merchant_user',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='is_active_user',
            new_name='is_active_in_merchant',
        ),
    ]
